sue445/regional-rb-calendar

- docs/config/doorkeeper.json
よろしくお願いします:pray:
https://entakurb.doorkeeper.jp/
> Add Entaku.rb

- docs/config/doorkeeper.json
https://maebashirb.doorkeeper.jp/
> Add Maebashi.rb

- docs/config/connpass.json
https://hirakatarb.connpass.com/
> Add Hirakata.rb

- docs/config/connpass.json
https://kokurarb.connpass.com/
> Add Kokura.rb

- .github/workflows/build.yml
> Deploy to Cloud Functions

- docs/config/connpass.json
cf. https://nagara-rb.connpass.com/
> Add nagara.rb

- docs/config/connpass.json
fukui.rb の追加です。
https://fukuirb.connpass.com/
```
$ curl -s https://fukuirb.connpass.com/ | grep "https://connpass.com/series/"
<input type="hidden" name="next" value="https://connpass.com/series/13530/?gmem=1" />
```
よろしくお願いします！
> fukui.rb 追加

- docs/config/doorkeeper.json
cf. https://rubytokai.doorkeeper.jp/
> Add Ruby東海

- docs/config/connpass.json
cf. https://mikanrb.connpass.com/
> Add みかん.rb

- docs/config/connpass.json
cf. https://kumamotorb.connpass.com/
> Add Kumamoto.rb

- docs/config/connpass.json
https://tottoruby.connpass.com/
> Add tottoruby

- docs/config/connpass.json
https://kyobashirb.connpass.com/
> Add Kyobashi.rb

- docs/config/connpass.json
Urawa.rbを追加しました。https://urawarb.connpass.com/
- series_idはREADME記載のcurlで取得しました。
- idはconnpassのURLから取得しました。(https://urawarb.connpass.com/)
```zsh
❯  curl -s https://urawarb.connpass.com/ | grep "https://connpass.com/series/"
<input type="hidden" name="next" value="https://connpass.com/series/14367/?gmem=1" />
```
お時間あるときにご確認いただけると幸いです 🙇
> Add Urawa.rb

- docs/index.html
> Add note for Connpass API

- .github/workflows/build.yml
> Use Serverlsss VPC Connector at GCF

- docs/index.html
> Fix alert message

- docs/config/connpass.json
cf. https://asakusa-bashi-rbs.connpass.com/
cf. https://shinmerb.connpass.com/
> Add Asakusa-bashi.rbs and しんめ.rb

- docs/config/connpass.json
cf. https://kashiwarb.connpass.com/
Kashiwa.rb is currently under construction. The first gathering will be held soon.
> Add Kashiwa.rb to connpass.json

- docs/config/connpass.json
cf. https://kyotorb.connpass.com/
Kyoto.rb has been using connpass since 2023/04/28.
cf. https://kyotorb.connpass.com/event/280236/
> Add Kyoto.rb to connpass.json

- docs/config/connpass.json
cf. https://akashi-rb.connpass.com/
AKASHI.rb has been founded, and its first meetup will take place on November 26, 2024.
cf. https://akashi-rb.connpass.com/event/337480/
> Add AKASHI.rb to connpass.json

- docs/config/connpass.json
cf. https://seto-rb.connpass.com/
> Add Seto.rb

- docs/config/connpass.json
新しく三浦半島.rbをカレンダーに登録させてください🙏
https://miurahantorb.connpass.com/
> Add Miurahanto.rb to connpass.json

- .github/workflows/build.yml
Reverts sue445/regional-rb-calendar#322
This has been needless
> Revert "Clear VPC connector"

- docs/config/connpass.json
やります!! 
<https://kofurb.connpass.com/event/355417/>
> Kofu.rbを追加

- docs/config/connpass.json
cf. https://picopicoruby.connpass.com/
cf. https://korb.connpass.com/
cf. https://shikumirb.connpass.com/
cf. https://wakate-rb.connpass.com/
> Add PicoPicoRuby and ko.rb and Shikumi.rb and Wakate.rb

- docs/config/connpass.json
https://railstokyo.connpass.com/
> Add RailsTokyo

- docs/config/connpass.json
- docs/config/doorkeeper.json
KOBE.rbがconnpassにお引越ししました！🙏
cf. https://koberb.doorkeeper.jp/
cf. https://koberb.connpass.com/
> Transfer KOBE.rb
